- hosts: all
  tasks:
    - name: stop container
      shell: docker container stop rockstar-container
    - name: remove container
      shell: docker container rm rockstar-container
    - name: remove docker image
      shell: docker image rmi soumya08/new_docker
    - name: create new container soumya08/new_docker
      shell: docker container run -itd --name rockstar-container -p 9000:80 soumya08/new_docker     #(docker-job>> name of jenkins job)
